site_name: Shinoa
repo_url: https://github.com/Gremagol/ShinoaCMDList
pages:
- Meet Shinoa: index.md
- Commands & Guides:
    - Commands List: Commands List.md   
    - Custom Reactions: Custom Reactions.md
    - Permission Guide: Permissions System.md
    - Placeholders: Placeholders.md

theme: readthedocs
