site_name: Shinoa
repo_url: https://github.com/Gremagol/ShinoaCMDList
pages:
- Home: index.md
- Commands and Reactions:
    - Commands List: Commands List.md   
    - Custom Reactions: Custom Reactions.md

theme: readthedocs
