site_name: Ene-Bot
repo_url: https://github.com/Gremagol/EneCMDList
pages:
- Meet Ene: index.md
- Commands & Guides:
    - Commands List: Commands List.md   
    - Custom Reactions: Custom Reactions.md
    - Permission Guide: Permissions System.md
    - Placeholders: Placeholders.md
- Music Guide:
    - Player: Player.md
    - Permissions: Permissions.md
    - Playlists: Playlists.md

theme: readthedocs
